# Site settings
title: Resources
header-img: img/home-bg.jpg
email: contact@dario.com
copyright_name:
description: "Security is a business requirement. Protecting privacy is good business. Understand the threats to your information - Take Action to protect your data and business."
baseurl: "/Resources"
url: "https://dario.pw"
twitter_username: darioS3C
github_username:
facebook_username:
email_username:  contact@dario.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-98131817-4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
